tcp_h_dir = ../../TCPINC/
tcp_c_dir = ../../TCPLIB/
common_h_dir = ../../INCLUDE
memory_model = -ml
compile_options = -0 $(memory_model) -DCFG_H=\"mtcpget.cfg\" -oh -ok -ot -s -oa -ei -zp2 -zpw -we -ob -ol+ -oi+
compile_options += -i=$(tcp_h_dir) -i=$(common_h_dir)

tcpobjs = packet.obj arp.obj eth.obj ip.obj tcp.obj tcpsockm.obj udp.obj utils.obj dns.obj timer.obj ipasm.obj trace.obj
objs = mtcpget.obj

all : mtcpget.exe

.asm : $(tcp_c_dir)
.cpp : $(tcp_c_dir)

.asm.obj :
  wasm -0 $(memory_model) -fo=$^@ $[*

.cpp.obj :
  wpp -fo=$^@ $[* $(compile_options)

mtcpget.exe: $(tcpobjs) $(objs)
  wlink @mtcpget.rsp
